### ISSUE TITLE
Simple CI/CD Deployment (Vercel + NPM Publishing)

### ISSUE THREAD

**Issue by mkwatson** [mkwatson/ai-fastify-template#35]
## 🎯 Objective

Implement simple deployment and publishing workflows that build on MAR-21 CI pipeline, providing immediate value while establishing patterns for MAR-32 enterprise deployment.

## 📋 Scope

**Simple, battle-tested deployment patterns:**

* Vercel deployment for frontend/docs (when available)
* NPM publishing for SDK packages (when available)
* Optional triggers based on environment variables
* Clear separation from core CI validation

### Phase 1: Optional Deployment Workflow

- [ ] Create `.github/workflows/deploy.yml` (separate from CI)
- [ ] Add Vercel deployment step (only if `VERCEL_TOKEN` exists)
- [ ] Add NPM publishing step (only if `NPM_TOKEN` exists)
- [ ] Ensure deployment only runs on `main` branch after CI passes

### Phase 2: Package Publishing

- [ ] Configure NPM publishing for SDK packages
- [ ] Add semantic versioning automation
- [ ] Add deployment status reporting
- [ ] Test with tokens in environment

## ✅ Acceptance Criteria

**Core Functionality:**

- [ ] Deployment workflow only runs after CI passes
- [ ] Vercel deployment works when `VERCEL_TOKEN` provided
- [ ] NPM publishing works when `NPM_TOKEN` provided
- [ ] No deployment attempt when tokens missing (graceful skip)
- [ ] Clear success/failure reporting

**Security & Best Practices:**

- [ ] Secrets properly configured in GitHub repository settings
- [ ] No hardcoded tokens or sensitive data
- [ ] Deployment runs only on protected `main` branch
- [ ] Proper error handling and rollback capabilities

### Workflow Structure

```yaml
name: Deploy
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vercel
        if: env.VERCEL_TOKEN
        # Vercel deployment logic
        
      - name: Publish to NPM  
        if: env.NPM_TOKEN
        # NPM publishing logic
```

### Environment Variables

* `VERCEL_TOKEN` (optional) - Vercel deployment
* `NPM_TOKEN` (optional) - NPM registry publishing
* `VERCEL_ORG_ID` (optional) - Vercel organization
* `VERCEL_PROJECT_ID` (optional) - Vercel project

## 📊 Success Metrics

* **Deployment reliability**: 99%+ success rate when tokens provided
* **Time to deployment**: < 5 minutes from merge to live
* **Zero broken deployments**: Proper validation before deployment
* **Clear visibility**: Status updates in Linear/Slack

## 🔮 Future Evolution

This ticket establishes patterns that MAR-32 will enhance:

* Simple → Enterprise deployment strategies
* Basic → Advanced monitoring and alerting
* Manual → Automated infrastructure management
* Single cloud → Multi-cloud deployment

## 🎯 Dependencies

**Requires:**

* MAR-21 (GitHub Actions CI) - must complete first
* Repository secrets configured for tokens

**Enables:**

* Immediate deployment capability
* Foundation for MAR-32 enterprise patterns
* Team workflow for continuous delivery
